apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
    app: postgresdb
spec:
  capacity:
    storage: 8Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
