version: '3'
services:
  peyk-container:
    image: precioux/peyk-server:latest

  bepa:
    image: marmary2001/bepa-service-image:1
    depends_on:
      - coinnews
    links:
      - coinnews

  coinnews:
    image: amirhossein21/coinnews.linux:v0.2
    ports:
      - "8000:8000"
    volumes:
      - ./config/config.yml:/go/src/app/config.yml
