apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: postgresdb
spec:
  type: ClusterIP
  selector:
    app: postgresdb
  ports:
    - name: postgresgb
      port: 5432
      targetPort: 5432
