apiVersion: v1
kind: Service
metadata:
  name: peyk-server-service
  labels:
    kubernetes.app: data-source
    app: peyk-server
spec:
  type: ClusterIP
  selector:
    app: peyk-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
