apiVersion: v1
kind: ConfigMap
metadata:
  name: bepa-service-configmap
data:
#  config.json: |-
#    {{ .Files.Get "../step2/config.json" | nindent 4 }}
  config.json: |-
    {
       "COIN_NEWS_HOST": "http://coinnews:8000/api/data"
    }
  message: 'You are connected!'