apiVersion: batch/v1
kind: CronJob
metadata:
  name: bepa-cronjob
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure  # Add this line
          containers:
            - name: bepa
              image: marmary2001/bepa-image-debug
#              imagePullPolicy: Never
              # Add any additional container configuration, environment variables, etc. as needed
              volumeMounts:
                - name: config
                  mountPath: app/config.json
                  subPath: config.json

          volumes:
            - name: config
              configMap:
                name: bepa-service-configmap
#                items:
#                  - key: configmap.yml
#                    path: configmap.yml
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
